/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as DraftPoolRouteImport } from './routes/draft-pool'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CardCardIdRouteImport } from './routes/card.$cardId'

const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftPoolRoute = DraftPoolRouteImport.update({
  id: '/draft-pool',
  path: '/draft-pool',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CardCardIdRoute = CardCardIdRouteImport.update({
  id: '/card/$cardId',
  path: '/card/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/database': typeof DatabaseRoute
  '/draft-pool': typeof DraftPoolRoute
  '/rules': typeof RulesRoute
  '/card/$cardId': typeof CardCardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/database': typeof DatabaseRoute
  '/draft-pool': typeof DraftPoolRoute
  '/rules': typeof RulesRoute
  '/card/$cardId': typeof CardCardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/database': typeof DatabaseRoute
  '/draft-pool': typeof DraftPoolRoute
  '/rules': typeof RulesRoute
  '/card/$cardId': typeof CardCardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/database' | '/draft-pool' | '/rules' | '/card/$cardId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/database' | '/draft-pool' | '/rules' | '/card/$cardId'
  id:
    | '__root__'
    | '/'
    | '/database'
    | '/draft-pool'
    | '/rules'
    | '/card/$cardId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatabaseRoute: typeof DatabaseRoute
  DraftPoolRoute: typeof DraftPoolRoute
  RulesRoute: typeof RulesRoute
  CardCardIdRoute: typeof CardCardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft-pool': {
      id: '/draft-pool'
      path: '/draft-pool'
      fullPath: '/draft-pool'
      preLoaderRoute: typeof DraftPoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$cardId': {
      id: '/card/$cardId'
      path: '/card/$cardId'
      fullPath: '/card/$cardId'
      preLoaderRoute: typeof CardCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatabaseRoute: DatabaseRoute,
  DraftPoolRoute: DraftPoolRoute,
  RulesRoute: RulesRoute,
  CardCardIdRoute: CardCardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
